ArtShop.WebSite/Controllers/ArtistController.cs
using ArtShop.Data.Model;
using ArtShop.Data.Services;
using ArtShop.WebSite.Services;
using ArtShop.WebSite.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArtShop.WebSite.Controllers
{
    [Authorize]
    public class ArtistController : BaseController
    {
        BaseDataService<Artist> db;

        public ArtistController()
        {
            db = new BaseDataService<Artist>();
        }
        public ActionResult Index()
        {
            var list = db.Get();
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Artist artist)
        {
            this.CheckAuditPattern(artist, true);
            var list = db.ValidateModel(artist);
            if (ModelIsInvalid(list))
            {
                return View(artist);
            }
            try
            {
                db.Create(artist);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex);
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var artist = db.GetById(id.Value);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        [HttpPost]
        public ActionResult Edit(Artist artist)
        {
            this.CheckAuditPattern(artist, true);
            var list = db.ValidateModel(artist);
            if (ModelIsInvalid(list))
            {
                return View(artist);
            }
            try
            {
                db.Update(artist);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex);
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var artist = db.GetById(id.Value);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        [HttpPost]
        public ActionResult Delete(Artist artist)
        {
            this.CheckAuditPattern(artist);
            var list = db.ValidateModel(artist);
            if (ModelIsInvalid(list))
            {
                return View(artist);
            }
            try
            {
                db.Delete(artist.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogException(ex);
                ViewBag.MessageDanger = ex.Message;
                return View(artist);
            }
        }
    }
}

ArtShop.WebSite/Views/Artist/Create.cshtml
@model ArtShop.Data.Model.Artist
@{
    ViewBag.Title = "Crear Artista";
}

<div class="post">
    <h2 class="title"><a href="#">Nuevo Artista</a></h2>
    <p class="byline">
        <h4>Artista</h4>
    </p>
    <div>
        @using (Html.BeginForm())
        {
            <div class="form">
                <hr />
                <span class="text-danger">@ViewBag.MessageDanger</span>
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName)
                    <div>
                        @Html.EditorFor(model => model.FirstName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName)
                    <div>
                        @Html.EditorFor(model => model.LastName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LifeSpan)
                    <div>
                        @Html.EditorFor(model => model.LifeSpan)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Country)
                    <div>
                        @Html.EditorFor(model => model.Country)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description)
                    <div>
                        @Html.EditorFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalProducts)
                    <div>
                        @Html.EditorFor(model => model.TotalProducts)
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <input type="submit" value="Guardar" class="btn-input" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div>
        @Html.ActionLink("Volver", "Index")
    </div>

</div>

ArtShop.WebSite/Views/Artist/Delete.cshtml
@model ArtShop.Data.Model.Artist
@{
    ViewBag.Title = "ELiminar Artista";
}

<div class="post">
    <h2 class="title"><a href="#"> Eliminar Artista</a></h2>
    <p class="byline">
        <h4>Profesional: @Model.FullName</h4>
    </p>
    <div>
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">

                <hr />
                <span class="text-danger">@ViewBag.MessageDanger</span>
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName)
                    <div>
                        @Html.EditorFor(model => model.FirstName)
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName)
                    <div>
                        @Html.EditorFor(model => model.LastName)
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LifeSpan)
                    <div>
                        @Html.EditorFor(model => model.LifeSpan)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Country)
                    <div>
                        @Html.EditorFor(model => model.Country)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description)
                    <div>
                        @Html.EditorFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalProducts)
                    <div>
                        @Html.EditorFor(model => model.TotalProducts)
                    </div>
                </div>
                @Html.HiddenFor(model => model.CreatedOn)
                @Html.HiddenFor(model => model.CreatedBy)
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Eliminar" />
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    </div>
</div>

ArtShop.WebSite/Views/Artist/Edit.cshtml
@model ArtShop.Data.Model.Artist
@{
    ViewBag.Title = "Editar Artista";
}

<div class="post">
    <h2 class="title"><a href="#"> Editar Artista</a></h2>
    <p class="byline">
        <h4>Profesional: @Model.FullName</h4>
    </p>
    <div>
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">

                <hr />
                <span class="text-danger">@ViewBag.MessageDanger</span>
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName)
                    <div>
                        @Html.EditorFor(model => model.FirstName)
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName)
                    <div>
                        @Html.EditorFor(model => model.LastName)
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LifeSpan)
                    <div>
                        @Html.EditorFor(model => model.LifeSpan)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Country)
                    <div>
                        @Html.EditorFor(model => model.Country)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description)
                    <div>
                        @Html.EditorFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalProducts)
                    <div>
                        @Html.EditorFor(model => model.TotalProducts)
                    </div>
                </div>
                @Html.HiddenFor(model => model.CreatedOn)
                @Html.HiddenFor(model => model.CreatedBy)
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Guardar" />
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    </div>
</div>

ArtShop.WebSite/Views/Artist/Index.cshtml
@model IEnumerable<ArtShop.Data.Model.Artist>
@{
    ViewBag.Title = "Index";
}

<aside>
    @Html.ActionLink("Nuevo Artista", "Create", "Artist")
</aside>
<article>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LifeSpan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalProducts)
            </th>
            <th>
                Operaciones
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(model => item.LifeSpan)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(model => item.TotalProducts)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</article>